### ISSUE TITLE
Separate delivery of activity json and workplace json from list view

### ISSUE THREAD

**Issue by fwild** [ARETEedu/moodle-mod_arete#106]
At the moment, the list contains also the full activity json array and the full workplace json array for every single item. This is very inefficient. MirageXR subsequently anyways fetches the zip file which contains these two. The activity and workplace json should of course be stored, but not be returned when fetching the list view.

**Comment by Callustian** [comment]
Hi @fwild 
The fields that are printed at this time are 
`id | contextid | fileid | userid | itemid | sessionid | filename | title | views | filesize | upublic | rate | activity_json | workplace_json | timecreated | timemodified | thumbnail
`
Is it only `activity_json` and `workplace_json` I have to exclude?
