### ISSUE TITLE
Ratings not saved (AR course activity repo list)

### ISSUE THREAD

**Issue by fwild** [ARETEedu/moodle-mod_arete#58]
Both star rating options (on top the assigned unit or down in the list) do only work visually, but the rating is not saved and the vote counter not increased.

**Comment by fwild** [comment]
The javascript console reports a 404 file not found for the insertRating.php link:
HR POST https://arete.ucd.ie/mod/arete/classes/insertRating.php?0.9981842332958144
[[HTTP/1.1 404 Not Found 163ms]]()

**Comment by Callustian** [comment]
Issues solved, and improvement added (#92 )
