### ISSUE TITLE
Check that tokens (for web service API access) are not expiring

### ISSUE THREAD

**Issue by fwild** [ARETEedu/moodle-mod_arete#80]
There have been issues in the past, that users reported access to the server as not working (from the app), which we tracked down to their web service access token having expired (although it was set to infinite duration!). This may have been fixed, but not sure whether this was fixed with manual intervention - generating new tokens for users with broken access. Please check!

**Comment by Callustian** [comment]
As you know at generation time you can establish if the token has to expire, and that has "false" as default (locally).

**Comment by fwild** [comment]
This is a bit dated, but has important comments: https://stackoverflow.com/questions/56262145/moodle-web-services-refresh-token

**Comment by Callustian** [comment]
Hi. I have read a bit of software.

In the context of webservices all checks of the token validity verify the validity is not 0 (I understand '0' means token does not expire).

In the case of expired tokens (I am unsure of how that would occur, possibly changing the expiry time), as the link you posted, the client does not have this information.
Are you asking me that the server generates a new token if the passed token has expired (I don't think so as this defies the meaning of expiry time) or that I implement in the client a request of a new token?

This seems a request to change the moodle sources to me and it is unrelated to the plugin.

A replicable case would greatly help. Thanks.

**Comment by Callustian** [comment]
Hi.
I am asking myself if we are speaking of the case a user can make tokens and the administrator did not generate a token for them.
In this case a token is generated all the times you ask for them using `token.php` rendering the old token obsolete.

**Comment by Callustian** [comment]
@fwild If you think the explanation I gave is reasonable, would you close this ticket? Thanks.

**Comment by fwild** [comment]
The problem seems not to have re-occurred so far. What used to happen last year was that suddenly many accounts stopped working from one day to another, and we finally tracked it down to expired tokens. Maybe Moodle changed something and it did not reappear? Its ok to close it, we should file a new one, in case the problem reappears!

**Comment by Callustian** [comment]
@fwild Thank you!
